# Generated by Django 3.2.6 on 2021-08-16 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lakmawi_home', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Sender',
            new_name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
