# Generated by Django 3.2.6 on 2021-08-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakmawi_home', '0005_auto_20210816_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='title',
        ),
    ]
