# Generated by Django 3.2.6 on 2021-08-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakmawi_home', '0007_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='a',
        ),
    ]
