# Generated by Django 3.2.6 on 2021-08-17 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakmawi_home', '0008_rename_author_post_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='a',
            new_name='author',
        ),
    ]
